// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/accesslog/v2/file.proto

package v2

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Custom configuration for an :ref:`AccessLog <envoy_api_msg_config.filter.accesslog.v2.AccessLog>`
// that writes log entries directly to a file. Configures the built-in *envoy.file_access_log*
// AccessLog.
type FileAccessLog struct {
	// A path to a local file to which to write the access log entries.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Access log format. Envoy supports :ref:`custom access log formats
	// <config_access_log_format>` as well as a :ref:`default format
	// <config_access_log_default_format>`.
	//
	// Types that are valid to be assigned to AccessLogFormat:
	//	*FileAccessLog_Format
	//	*FileAccessLog_JsonFormat
	AccessLogFormat      isFileAccessLog_AccessLogFormat `protobuf_oneof:"access_log_format"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *FileAccessLog) Reset()         { *m = FileAccessLog{} }
func (m *FileAccessLog) String() string { return proto.CompactTextString(m) }
func (*FileAccessLog) ProtoMessage()    {}
func (*FileAccessLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb42a04cfa71ce3c, []int{0}
}

func (m *FileAccessLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileAccessLog.Unmarshal(m, b)
}
func (m *FileAccessLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileAccessLog.Marshal(b, m, deterministic)
}
func (m *FileAccessLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileAccessLog.Merge(m, src)
}
func (m *FileAccessLog) XXX_Size() int {
	return xxx_messageInfo_FileAccessLog.Size(m)
}
func (m *FileAccessLog) XXX_DiscardUnknown() {
	xxx_messageInfo_FileAccessLog.DiscardUnknown(m)
}

var xxx_messageInfo_FileAccessLog proto.InternalMessageInfo

func (m *FileAccessLog) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type isFileAccessLog_AccessLogFormat interface {
	isFileAccessLog_AccessLogFormat()
}

type FileAccessLog_Format struct {
	Format string `protobuf:"bytes,2,opt,name=format,proto3,oneof"`
}

type FileAccessLog_JsonFormat struct {
	JsonFormat *_struct.Struct `protobuf:"bytes,3,opt,name=json_format,json=jsonFormat,proto3,oneof"`
}

func (*FileAccessLog_Format) isFileAccessLog_AccessLogFormat() {}

func (*FileAccessLog_JsonFormat) isFileAccessLog_AccessLogFormat() {}

func (m *FileAccessLog) GetAccessLogFormat() isFileAccessLog_AccessLogFormat {
	if m != nil {
		return m.AccessLogFormat
	}
	return nil
}

func (m *FileAccessLog) GetFormat() string {
	if x, ok := m.GetAccessLogFormat().(*FileAccessLog_Format); ok {
		return x.Format
	}
	return ""
}

func (m *FileAccessLog) GetJsonFormat() *_struct.Struct {
	if x, ok := m.GetAccessLogFormat().(*FileAccessLog_JsonFormat); ok {
		return x.JsonFormat
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FileAccessLog) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FileAccessLog_Format)(nil),
		(*FileAccessLog_JsonFormat)(nil),
	}
}

func init() {
	proto.RegisterType((*FileAccessLog)(nil), "envoy.config.accesslog.v2.FileAccessLog")
}

func init() {
	proto.RegisterFile("envoy/config/accesslog/v2/file.proto", fileDescriptor_bb42a04cfa71ce3c)
}

var fileDescriptor_bb42a04cfa71ce3c = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xeb, 0xb4, 0xaa, 0x14, 0x57, 0x0c, 0x84, 0xa1, 0xa1, 0x02, 0x29, 0x42, 0x48, 0x74,
	0x3a, 0x4b, 0x61, 0xeb, 0x46, 0x86, 0xaa, 0x03, 0x43, 0x15, 0x36, 0x96, 0xca, 0x0d, 0x8e, 0x31,
	0x32, 0xb9, 0xc8, 0x71, 0x2d, 0xfa, 0x28, 0xbc, 0x0a, 0x13, 0xaf, 0xc3, 0x5b, 0xa0, 0xd8, 0x29,
	0x1b, 0x9b, 0xcf, 0xf7, 0xdd, 0xff, 0xe9, 0xa7, 0xb7, 0xa2, 0x71, 0x78, 0x64, 0x15, 0x36, 0xb5,
	0x92, 0x8c, 0x57, 0x95, 0xe8, 0x3a, 0x8d, 0x92, 0xb9, 0x9c, 0xd5, 0x4a, 0x0b, 0x68, 0x0d, 0x5a,
	0x4c, 0x2e, 0x3d, 0x05, 0x81, 0x82, 0x3f, 0x0a, 0x5c, 0xbe, 0x98, 0x3b, 0xae, 0xd5, 0x0b, 0xb7,
	0x82, 0x9d, 0x1e, 0xe1, 0x66, 0x71, 0x25, 0x11, 0xa5, 0x16, 0xcc, 0x4f, 0xfb, 0x43, 0xcd, 0x3a,
	0x6b, 0x0e, 0x95, 0x0d, 0xdb, 0x9b, 0x4f, 0x42, 0xcf, 0xd6, 0x4a, 0x8b, 0x07, 0x9f, 0xf5, 0x88,
	0x32, 0xb9, 0xa6, 0x93, 0x96, 0xdb, 0xd7, 0x94, 0x64, 0x64, 0x19, 0x17, 0xf1, 0xd7, 0xcf, 0xf7,
	0x78, 0x62, 0xa2, 0x8c, 0x94, 0xfe, 0x3b, 0x49, 0xe9, 0xb4, 0x46, 0xf3, 0xce, 0x6d, 0x1a, 0xf5,
	0xc0, 0x66, 0x54, 0x0e, 0x73, 0xb2, 0xa2, 0xb3, 0xb7, 0x0e, 0x9b, 0xdd, 0xb0, 0x1e, 0x67, 0x64,
	0x39, 0xcb, 0xe7, 0x10, 0xf4, 0x70, 0xd2, 0xc3, 0x93, 0xd7, 0x6f, 0x46, 0x25, 0xed, 0xe9, 0xb5,
	0x87, 0x8b, 0x0b, 0x7a, 0x1e, 0xda, 0xec, 0x34, 0xca, 0x21, 0xa1, 0x58, 0xd1, 0x3b, 0x85, 0xe0,
	0x2b, 0xb7, 0x06, 0x3f, 0x8e, 0xf0, 0x6f, 0xfb, 0x22, 0xee, 0x3b, 0x6c, 0x7b, 0xc5, 0x96, 0x3c,
	0x47, 0x2e, 0xdf, 0x4f, 0xbd, 0xef, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0xff, 0x91, 0x89, 0xd3,
	0x58, 0x01, 0x00, 0x00,
}
