#
# Pre-built cilium-envoy image
#
FROM quay.io/cilium/cilium-envoy:74a21763dce81def53aef3a76ccc794bd9a062ad as cilium-envoy

FROM istio/proxytproxy:@ISTIO_VERSION@

# Istio image runs on Xenial, which has too old glibc for Envoy built on Bionic
# As a stopgap measure update the glibc to the required version (2.27)
RUN echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu bionic main" | tee /etc/apt/sources.list.d/bionic.list \
    && apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		libc6=2.27-3ubuntu1 \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Replace Istio's Envoy binary with Cilium's.
COPY --from=cilium-envoy /usr/bin/cilium-envoy /usr/local/bin/envoy

# pilot-agent and envoy may run with effective uid 0 in order to run envoy with
# CAP_NET_ADMIN, so any iptables rule matching on "-m owner --uid-owner
# istio-proxy" will not match connections from those processes anymore.
# Instead, rely on the process's effective gid being istio-proxy and create a
# "-m owner --gid-owner istio-proxy" iptables rule in istio-iptables.sh.
RUN \
chgrp 1337 /usr/local/bin/envoy && \
chmod 2755 /usr/local/bin/envoy

# Override the Envoy bootstrap to configure Envoy to use API v2 and to define
# the "xds-grpc-cilium" cluster used by the Cilium filters to connect to Cilium
# agent via a Unix domain socket.
# This file is adapted from Istio's API v2 bootstrap:
# $ wget https://raw.githubusercontent.com/istio/istio/1.2.2/tools/packaging/common/envoy_bootstrap_v2.json
# $ patch -o envoy_bootstrap_tmpl.json < envoy_bootstrap_v2.patch
COPY envoy_bootstrap_tmpl.json /var/lib/istio/envoy/envoy_bootstrap_tmpl.json

ENTRYPOINT ["/usr/local/bin/pilot-agent"]
