// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: envoy/extensions/filters/listener/tls_inspector/v3/tls_inspector.proto

package tls_inspectorv3

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TlsInspector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Populate “JA3“ fingerprint hash using data from the TLS Client Hello packet. Default is false.
	EnableJa3Fingerprinting *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=enable_ja3_fingerprinting,json=enableJa3Fingerprinting,proto3" json:"enable_ja3_fingerprinting,omitempty"`
	// The size in bytes of the initial buffer requested by the tls_inspector.
	// If the filter needs to read additional bytes from the socket, the
	// filter will double the buffer up to it's default maximum of 64KiB.
	// If this size is not defined, defaults to maximum 64KiB that the
	// tls inspector will consume.
	InitialReadBufferSize *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=initial_read_buffer_size,json=initialReadBufferSize,proto3" json:"initial_read_buffer_size,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TlsInspector) Reset() {
	*x = TlsInspector{}
	mi := &file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsInspector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsInspector) ProtoMessage() {}

func (x *TlsInspector) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsInspector.ProtoReflect.Descriptor instead.
func (*TlsInspector) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDescGZIP(), []int{0}
}

func (x *TlsInspector) GetEnableJa3Fingerprinting() *wrapperspb.BoolValue {
	if x != nil {
		return x.EnableJa3Fingerprinting
	}
	return nil
}

func (x *TlsInspector) GetInitialReadBufferSize() *wrapperspb.UInt32Value {
	if x != nil {
		return x.InitialReadBufferSize
	}
	return nil
}

var File_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto protoreflect.FileDescriptor

const file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDesc = "" +
	"\n" +
	"Fenvoy/extensions/filters/listener/tls_inspector/v3/tls_inspector.proto\x122envoy.extensions.filters.listener.tls_inspector.v3\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dudpa/annotations/status.proto\x1a!udpa/annotations/versioning.proto\x1a\x17validate/validate.proto\"\x8e\x02\n" +
	"\fTlsInspector\x12V\n" +
	"\x19enable_ja3_fingerprinting\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\x17enableJa3Fingerprinting\x12c\n" +
	"\x18initial_read_buffer_size\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueB\f\xfaB\t*\a\x10\x81\x80\x04 \xff\x01R\x15initialReadBufferSize:A\x9aň\x1e<\n" +
	":envoy.config.filter.listener.tls_inspector.v2.TlsInspectorB\xca\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"@io.envoyproxy.envoy.extensions.filters.listener.tls_inspector.v3B\x11TlsInspectorProtoP\x01Zigithub.com/envoyproxy/go-control-plane/envoy/extensions/filters/listener/tls_inspector/v3;tls_inspectorv3b\x06proto3"

var (
	file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDescOnce sync.Once
	file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDescData []byte
)

func file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDescGZIP() []byte {
	file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDescOnce.Do(func() {
		file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDesc), len(file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDesc)))
	})
	return file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDescData
}

var file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_goTypes = []any{
	(*TlsInspector)(nil),           // 0: envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
	(*wrapperspb.BoolValue)(nil),   // 1: google.protobuf.BoolValue
	(*wrapperspb.UInt32Value)(nil), // 2: google.protobuf.UInt32Value
}
var file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_depIdxs = []int32{
	1, // 0: envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector.enable_ja3_fingerprinting:type_name -> google.protobuf.BoolValue
	2, // 1: envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector.initial_read_buffer_size:type_name -> google.protobuf.UInt32Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_init() }
func file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_init() {
	if File_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDesc), len(file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_goTypes,
		DependencyIndexes: file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_depIdxs,
		MessageInfos:      file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_msgTypes,
	}.Build()
	File_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto = out.File
	file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_goTypes = nil
	file_envoy_extensions_filters_listener_tls_inspector_v3_tls_inspector_proto_depIdxs = nil
}
