// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/filter/network/redis_proxy/v2/redis_proxy.proto

package v2

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/lyft/protoc-gen-validate/validate"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RedisProxy struct {
	// The prefix to use when emitting :ref:`statistics <config_network_filters_redis_proxy_stats>`.
	StatPrefix string `protobuf:"bytes,1,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	// Name of cluster from cluster manager. See the :ref:`configuration section
	// <arch_overview_redis_configuration>` of the architecture overview for recommendations on
	// configuring the backing cluster.
	//
	// .. attention::
	//
	//   This field is deprecated. Use a :ref:`catch-all
	//   cluster<envoy_api_field_config.filter.network.redis_proxy.v2.RedisProxy.PrefixRoutes.catch_all_cluster>`
	//   instead.
	Cluster string `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"` // Deprecated: Do not use.
	// Network settings for the connection pool to the upstream clusters.
	Settings *RedisProxy_ConnPoolSettings `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	// Indicates that latency stat should be computed in microseconds. By default it is computed in
	// milliseconds.
	LatencyInMicros bool `protobuf:"varint,4,opt,name=latency_in_micros,json=latencyInMicros,proto3" json:"latency_in_micros,omitempty"`
	// List of **unique** prefixes used to separate keys from different workloads to different
	// clusters. Envoy will always favor the longest match first in case of overlap. A catch-all
	// cluster can be used to forward commands when there is no match. Time complexity of the
	// lookups are in O(min(longest key prefix, key length)).
	//
	// Example:
	//
	// .. code-block:: yaml
	//
	//    prefix_routes:
	//      routes:
	//        - prefix: "ab"
	//          cluster: "cluster_a"
	//        - prefix: "abc"
	//          cluster: "cluster_b"
	//
	// When using the above routes, the following prefixes would be sent to:
	//
	// * 'get abc:users' would retrive the key 'abc:users' from cluster_b.
	// * 'get ab:users' would retrive the key 'ab:users' from cluster_a.
	// * 'get z:users' would return a NoUpstreamHost error. A :ref:`catch-all
	//   cluster<envoy_api_field_config.filter.network.redis_proxy.v2.RedisProxy.PrefixRoutes.catch_all_cluster>`
	//   would have retrieved the key from that cluster instead.
	//
	// See the :ref:`configuration section
	// <arch_overview_redis_configuration>` of the architecture overview for recommendations on
	// configuring the backing clusters.
	PrefixRoutes         *RedisProxy_PrefixRoutes `protobuf:"bytes,5,opt,name=prefix_routes,json=prefixRoutes,proto3" json:"prefix_routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RedisProxy) Reset()         { *m = RedisProxy{} }
func (m *RedisProxy) String() string { return proto.CompactTextString(m) }
func (*RedisProxy) ProtoMessage()    {}
func (*RedisProxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_67e7179f1292d5ae, []int{0}
}

func (m *RedisProxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisProxy.Unmarshal(m, b)
}
func (m *RedisProxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisProxy.Marshal(b, m, deterministic)
}
func (m *RedisProxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisProxy.Merge(m, src)
}
func (m *RedisProxy) XXX_Size() int {
	return xxx_messageInfo_RedisProxy.Size(m)
}
func (m *RedisProxy) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisProxy.DiscardUnknown(m)
}

var xxx_messageInfo_RedisProxy proto.InternalMessageInfo

func (m *RedisProxy) GetStatPrefix() string {
	if m != nil {
		return m.StatPrefix
	}
	return ""
}

// Deprecated: Do not use.
func (m *RedisProxy) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *RedisProxy) GetSettings() *RedisProxy_ConnPoolSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *RedisProxy) GetLatencyInMicros() bool {
	if m != nil {
		return m.LatencyInMicros
	}
	return false
}

func (m *RedisProxy) GetPrefixRoutes() *RedisProxy_PrefixRoutes {
	if m != nil {
		return m.PrefixRoutes
	}
	return nil
}

// Redis connection pool settings.
type RedisProxy_ConnPoolSettings struct {
	// Per-operation timeout in milliseconds. The timer starts when the first
	// command of a pipeline is written to the backend connection. Each response received from Redis
	// resets the timer since it signifies that the next command is being processed by the backend.
	// The only exception to this behavior is when a connection to a backend is not yet established.
	// In that case, the connect timeout on the cluster will govern the timeout until the connection
	// is ready.
	OpTimeout *duration.Duration `protobuf:"bytes,1,opt,name=op_timeout,json=opTimeout,proto3" json:"op_timeout,omitempty"`
	// Use hash tagging on every redis key to guarantee that keys with the same hash tag will be
	// forwarded to the same upstream. The hash key used for determining the upstream in a
	// consistent hash ring configuration will be computed from the hash tagged key instead of the
	// whole key. The algorithm used to compute the hash tag is identical to the `redis-cluster
	// implementation <https://redis.io/topics/cluster-spec#keys-hash-tags>`_.
	//
	// Examples:
	//
	// * '{user1000}.following' and '{user1000}.followers' **will** be sent to the same upstream
	// * '{user1000}.following' and '{user1001}.following' **might** be sent to the same upstream
	EnableHashtagging bool `protobuf:"varint,2,opt,name=enable_hashtagging,json=enableHashtagging,proto3" json:"enable_hashtagging,omitempty"`
	// Accept `moved and ask redirection
	// <https://redis.io/topics/cluster-spec#redirection-and-resharding>`_ errors from upstream
	// redis servers, and retry commands to the specified target server. The target server does not
	// need to be known to the cluster manager. If the command cannot be redirected, then the
	// original error is passed downstream unchanged. By default, this support is not enabled.
	EnableRedirection bool `protobuf:"varint,3,opt,name=enable_redirection,json=enableRedirection,proto3" json:"enable_redirection,omitempty"`
	// Maximum size of encoded request buffer before flush is triggered and encoded requests
	// are sent upstream. If this is unset, the buffer flushes whenever it receives data
	// and performs no batching.
	// This feature makes it possible for multiple clients to send requests to Envoy and have
	// them batched- for example if one is running several worker processes, each with its own
	// Redis connection. There is no benefit to using this with a single downstream process.
	// Recommended size (if enabled) is 1024 bytes.
	MaxBufferSizeBeforeFlush uint32 `protobuf:"varint,4,opt,name=max_buffer_size_before_flush,json=maxBufferSizeBeforeFlush,proto3" json:"max_buffer_size_before_flush,omitempty"`
	// The encoded request buffer is flushed N milliseconds after the first request has been
	// encoded, unless the buffer size has already exceeded `max_buffer_size_before_flush`.
	// If `max_buffer_size_before_flush` is not set, this flush timer is not used. Otherwise,
	// the timer should be set according to the number of clients, overall request rate and
	// desired maximum latency for a single command. For example, if there are many requests
	// being batched together at a high rate, the buffer will likely be filled before the timer
	// fires. Alternatively, if the request rate is lower the buffer will not be filled as often
	// before the timer fires.
	// If `max_buffer_size_before_flush` is set, but `buffer_flush_timeout` is not, the latter
	// defaults to 3ms.
	BufferFlushTimeout   *duration.Duration `protobuf:"bytes,5,opt,name=buffer_flush_timeout,json=bufferFlushTimeout,proto3" json:"buffer_flush_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RedisProxy_ConnPoolSettings) Reset()         { *m = RedisProxy_ConnPoolSettings{} }
func (m *RedisProxy_ConnPoolSettings) String() string { return proto.CompactTextString(m) }
func (*RedisProxy_ConnPoolSettings) ProtoMessage()    {}
func (*RedisProxy_ConnPoolSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_67e7179f1292d5ae, []int{0, 0}
}

func (m *RedisProxy_ConnPoolSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisProxy_ConnPoolSettings.Unmarshal(m, b)
}
func (m *RedisProxy_ConnPoolSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisProxy_ConnPoolSettings.Marshal(b, m, deterministic)
}
func (m *RedisProxy_ConnPoolSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisProxy_ConnPoolSettings.Merge(m, src)
}
func (m *RedisProxy_ConnPoolSettings) XXX_Size() int {
	return xxx_messageInfo_RedisProxy_ConnPoolSettings.Size(m)
}
func (m *RedisProxy_ConnPoolSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisProxy_ConnPoolSettings.DiscardUnknown(m)
}

var xxx_messageInfo_RedisProxy_ConnPoolSettings proto.InternalMessageInfo

func (m *RedisProxy_ConnPoolSettings) GetOpTimeout() *duration.Duration {
	if m != nil {
		return m.OpTimeout
	}
	return nil
}

func (m *RedisProxy_ConnPoolSettings) GetEnableHashtagging() bool {
	if m != nil {
		return m.EnableHashtagging
	}
	return false
}

func (m *RedisProxy_ConnPoolSettings) GetEnableRedirection() bool {
	if m != nil {
		return m.EnableRedirection
	}
	return false
}

func (m *RedisProxy_ConnPoolSettings) GetMaxBufferSizeBeforeFlush() uint32 {
	if m != nil {
		return m.MaxBufferSizeBeforeFlush
	}
	return 0
}

func (m *RedisProxy_ConnPoolSettings) GetBufferFlushTimeout() *duration.Duration {
	if m != nil {
		return m.BufferFlushTimeout
	}
	return nil
}

type RedisProxy_PrefixRoutes struct {
	// List of prefix routes.
	Routes []*RedisProxy_PrefixRoutes_Route `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	// Indicates that prefix matching should be case insensitive.
	CaseInsensitive bool `protobuf:"varint,2,opt,name=case_insensitive,json=caseInsensitive,proto3" json:"case_insensitive,omitempty"`
	// Optional catch-all route to forward commands that doesn't match any of the routes. The
	// catch-all route becomes required when no routes are specified.
	CatchAllCluster      string   `protobuf:"bytes,3,opt,name=catch_all_cluster,json=catchAllCluster,proto3" json:"catch_all_cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisProxy_PrefixRoutes) Reset()         { *m = RedisProxy_PrefixRoutes{} }
func (m *RedisProxy_PrefixRoutes) String() string { return proto.CompactTextString(m) }
func (*RedisProxy_PrefixRoutes) ProtoMessage()    {}
func (*RedisProxy_PrefixRoutes) Descriptor() ([]byte, []int) {
	return fileDescriptor_67e7179f1292d5ae, []int{0, 1}
}

func (m *RedisProxy_PrefixRoutes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisProxy_PrefixRoutes.Unmarshal(m, b)
}
func (m *RedisProxy_PrefixRoutes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisProxy_PrefixRoutes.Marshal(b, m, deterministic)
}
func (m *RedisProxy_PrefixRoutes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisProxy_PrefixRoutes.Merge(m, src)
}
func (m *RedisProxy_PrefixRoutes) XXX_Size() int {
	return xxx_messageInfo_RedisProxy_PrefixRoutes.Size(m)
}
func (m *RedisProxy_PrefixRoutes) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisProxy_PrefixRoutes.DiscardUnknown(m)
}

var xxx_messageInfo_RedisProxy_PrefixRoutes proto.InternalMessageInfo

func (m *RedisProxy_PrefixRoutes) GetRoutes() []*RedisProxy_PrefixRoutes_Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *RedisProxy_PrefixRoutes) GetCaseInsensitive() bool {
	if m != nil {
		return m.CaseInsensitive
	}
	return false
}

func (m *RedisProxy_PrefixRoutes) GetCatchAllCluster() string {
	if m != nil {
		return m.CatchAllCluster
	}
	return ""
}

type RedisProxy_PrefixRoutes_Route struct {
	// String prefix that must match the beginning of the keys. Envoy will always favor the
	// longest match.
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Indicates if the prefix needs to be removed from the key when forwarded.
	RemovePrefix bool `protobuf:"varint,2,opt,name=remove_prefix,json=removePrefix,proto3" json:"remove_prefix,omitempty"`
	// Upstream cluster to forward the command to.
	Cluster              string   `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisProxy_PrefixRoutes_Route) Reset()         { *m = RedisProxy_PrefixRoutes_Route{} }
func (m *RedisProxy_PrefixRoutes_Route) String() string { return proto.CompactTextString(m) }
func (*RedisProxy_PrefixRoutes_Route) ProtoMessage()    {}
func (*RedisProxy_PrefixRoutes_Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_67e7179f1292d5ae, []int{0, 1, 0}
}

func (m *RedisProxy_PrefixRoutes_Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisProxy_PrefixRoutes_Route.Unmarshal(m, b)
}
func (m *RedisProxy_PrefixRoutes_Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisProxy_PrefixRoutes_Route.Marshal(b, m, deterministic)
}
func (m *RedisProxy_PrefixRoutes_Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisProxy_PrefixRoutes_Route.Merge(m, src)
}
func (m *RedisProxy_PrefixRoutes_Route) XXX_Size() int {
	return xxx_messageInfo_RedisProxy_PrefixRoutes_Route.Size(m)
}
func (m *RedisProxy_PrefixRoutes_Route) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisProxy_PrefixRoutes_Route.DiscardUnknown(m)
}

var xxx_messageInfo_RedisProxy_PrefixRoutes_Route proto.InternalMessageInfo

func (m *RedisProxy_PrefixRoutes_Route) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *RedisProxy_PrefixRoutes_Route) GetRemovePrefix() bool {
	if m != nil {
		return m.RemovePrefix
	}
	return false
}

func (m *RedisProxy_PrefixRoutes_Route) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func init() {
	proto.RegisterType((*RedisProxy)(nil), "envoy.config.filter.network.redis_proxy.v2.RedisProxy")
	proto.RegisterType((*RedisProxy_ConnPoolSettings)(nil), "envoy.config.filter.network.redis_proxy.v2.RedisProxy.ConnPoolSettings")
	proto.RegisterType((*RedisProxy_PrefixRoutes)(nil), "envoy.config.filter.network.redis_proxy.v2.RedisProxy.PrefixRoutes")
	proto.RegisterType((*RedisProxy_PrefixRoutes_Route)(nil), "envoy.config.filter.network.redis_proxy.v2.RedisProxy.PrefixRoutes.Route")
}

func init() {
	proto.RegisterFile("envoy/config/filter/network/redis_proxy/v2/redis_proxy.proto", fileDescriptor_67e7179f1292d5ae)
}

var fileDescriptor_67e7179f1292d5ae = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc6, 0x59, 0xbb, 0xb5, 0xee, 0xc6, 0x36, 0x6b, 0x12, 0xa1, 0x9a, 0x58, 0x81, 0x4b, 0x99,
	0x44, 0x22, 0x95, 0x0b, 0x07, 0x84, 0x44, 0x86, 0x60, 0x3b, 0x20, 0x75, 0x19, 0x27, 0x2e, 0x96,
	0x9b, 0x39, 0xa9, 0x45, 0x6a, 0x57, 0xb6, 0x13, 0xba, 0x3d, 0x02, 0x4f, 0xc0, 0x33, 0xf0, 0x08,
	0x9c, 0x38, 0x70, 0xe0, 0xc2, 0x2b, 0xc0, 0x99, 0x57, 0xe0, 0x84, 0x6c, 0x27, 0x6d, 0x40, 0x42,
	0x4c, 0x88, 0x53, 0xdd, 0xff, 0xfb, 0xfe, 0xff, 0xf7, 0xf7, 0x7d, 0x31, 0x7c, 0x44, 0x79, 0x29,
	0x2e, 0xc2, 0x44, 0xf0, 0x94, 0x65, 0x61, 0xca, 0x72, 0x4d, 0x65, 0xc8, 0xa9, 0x7e, 0x23, 0xe4,
	0xeb, 0x50, 0xd2, 0x73, 0xa6, 0xf0, 0x5c, 0x8a, 0xc5, 0x45, 0x58, 0x8e, 0x9a, 0x7f, 0x83, 0xb9,
	0x14, 0x5a, 0xa0, 0x43, 0xdb, 0x1d, 0xb8, 0xee, 0xc0, 0x75, 0x07, 0x55, 0x77, 0xd0, 0xa4, 0x97,
	0xa3, 0xfe, 0xad, 0x4c, 0x88, 0x2c, 0xa7, 0xa1, 0xed, 0x9c, 0x14, 0x69, 0x78, 0x5e, 0x48, 0xa2,
	0x99, 0xe0, 0x6e, 0x56, 0xff, 0x46, 0x49, 0x72, 0x76, 0x4e, 0x34, 0x0d, 0xeb, 0x43, 0x05, 0xec,
	0x65, 0x22, 0x13, 0xf6, 0x18, 0x9a, 0x93, 0xab, 0xde, 0xf9, 0xb1, 0x01, 0x61, 0x6c, 0x36, 0x8c,
	0xcd, 0x02, 0x74, 0x08, 0x7b, 0x4a, 0x13, 0x8d, 0xe7, 0x92, 0xa6, 0x6c, 0xe1, 0x83, 0x01, 0x18,
	0x76, 0xa3, 0xee, 0x87, 0xef, 0x1f, 0xd7, 0x5a, 0xd2, 0x1b, 0x80, 0x18, 0x1a, 0x74, 0x6c, 0x41,
	0xb4, 0x0f, 0x37, 0x92, 0xbc, 0x50, 0x9a, 0x4a, 0xdf, 0xb3, 0x3c, 0xcf, 0x07, 0x71, 0x5d, 0x42,
	0x02, 0x76, 0x14, 0xd5, 0x9a, 0xf1, 0x4c, 0xf9, 0x6b, 0x03, 0x30, 0xec, 0x8d, 0x9e, 0x07, 0x57,
	0x97, 0x19, 0xac, 0xee, 0x14, 0x1c, 0x09, 0xce, 0xc7, 0x42, 0xe4, 0x67, 0xd5, 0xb8, 0x08, 0x9a,
	0xfb, 0xb4, 0xdf, 0x02, 0x6f, 0x07, 0xc4, 0xcb, 0x25, 0xe8, 0x10, 0xee, 0xe6, 0x44, 0x53, 0x9e,
	0x5c, 0x60, 0xc6, 0xf1, 0x8c, 0x25, 0x52, 0x28, 0xbf, 0x35, 0x00, 0xc3, 0x4e, 0xbc, 0x5d, 0x01,
	0x27, 0xfc, 0x85, 0x2d, 0x23, 0x0e, 0xb7, 0x9c, 0x42, 0x2c, 0x45, 0xa1, 0xa9, 0xf2, 0xdb, 0xf6,
	0x86, 0x47, 0xff, 0x78, 0x43, 0x67, 0x48, 0x6c, 0x47, 0x45, 0xad, 0xcf, 0x5f, 0x0f, 0xae, 0xc5,
	0x9b, 0xf3, 0x46, 0xad, 0xff, 0xc5, 0x83, 0x3b, 0xbf, 0xcb, 0x40, 0xc7, 0x10, 0x8a, 0x39, 0xd6,
	0x6c, 0x46, 0x45, 0xa1, 0xad, 0xd5, 0xbd, 0xd1, 0xcd, 0xc0, 0xc5, 0x1b, 0xd4, 0xf1, 0x06, 0x4f,
	0xab, 0x78, 0xa3, 0xeb, 0xef, 0xbe, 0x1d, 0x00, 0xab, 0xfc, 0x3d, 0xf0, 0x3a, 0x20, 0xee, 0x8a,
	0xf9, 0x4b, 0xd7, 0x8b, 0xee, 0x43, 0x44, 0x39, 0x99, 0xe4, 0x14, 0x4f, 0x89, 0x9a, 0x6a, 0x92,
	0x65, 0x8c, 0x67, 0x36, 0x94, 0x4e, 0xbc, 0xeb, 0x90, 0xe3, 0x15, 0xd0, 0xa0, 0x1b, 0x49, 0x92,
	0x26, 0x66, 0xbe, 0x0d, 0x69, 0x49, 0x8f, 0x57, 0x00, 0x7a, 0x0c, 0xf7, 0x67, 0x64, 0x81, 0x27,
	0x45, 0x9a, 0x52, 0x89, 0x15, 0xbb, 0xa4, 0x78, 0x42, 0x53, 0x21, 0x29, 0x4e, 0xf3, 0x42, 0x4d,
	0xad, 0xc7, 0x5b, 0xb1, 0x3f, 0x23, 0x8b, 0xc8, 0x52, 0xce, 0xd8, 0x25, 0x8d, 0x2c, 0xe1, 0x99,
	0xc1, 0xd1, 0x29, 0xdc, 0xab, 0x7a, 0x2d, 0x7f, 0xa9, 0xb8, 0xfd, 0x37, 0xc5, 0x2d, 0xa3, 0x38,
	0x46, 0xae, 0xd9, 0xce, 0xaa, 0x04, 0xf7, 0x3f, 0x79, 0x70, 0xb3, 0x69, 0x3a, 0xca, 0xe0, 0x7a,
	0x95, 0x24, 0x18, 0xac, 0x0d, 0x7b, 0xa3, 0x93, 0xff, 0x90, 0x64, 0x60, 0x7f, 0xaa, 0x3c, 0xab,
	0xf1, 0xe8, 0x1e, 0xdc, 0x49, 0x88, 0xa2, 0x98, 0x71, 0x45, 0xb9, 0x62, 0x9a, 0x95, 0xb4, 0x32,
	0x7a, 0xdb, 0xd4, 0x4f, 0x56, 0x65, 0xf3, 0x41, 0x26, 0x44, 0x27, 0x53, 0x4c, 0xf2, 0x1c, 0xd7,
	0x2f, 0xc5, 0xb8, 0xdc, 0x35, 0x5c, 0x9d, 0x4c, 0x9f, 0xe4, 0xf9, 0x91, 0x2b, 0xf7, 0x35, 0x6c,
	0xdb, 0x6d, 0xe8, 0x36, 0x5c, 0xff, 0xd3, 0xdb, 0xab, 0x00, 0x74, 0x17, 0x6e, 0x49, 0x3a, 0x13,
	0x25, 0xad, 0x5f, 0xa9, 0xdb, 0xbf, 0xe9, 0x8a, 0xe3, 0x9a, 0xb4, 0xf1, 0xcb, 0xca, 0xe6, 0xa0,
	0x1a, 0x89, 0x4e, 0xe1, 0x43, 0x26, 0x9c, 0x53, 0xce, 0x8c, 0xab, 0x9b, 0x16, 0x6d, 0xaf, 0x5c,
	0x1b, 0x9b, 0xe4, 0xc6, 0xe0, 0x95, 0x57, 0x8e, 0x26, 0xeb, 0x36, 0xc6, 0x07, 0x3f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0xb5, 0x9b, 0x97, 0x11, 0x05, 0x00, 0x00,
}
