name: CI Build & Push
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push-prs:
    timeout-minutes: 360
    name: Build and push multi-arch images
    runs-on: ubuntu-latest-64-cores-256gb
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6a58db7e0d21ca03e6c44877909e80e45217eed2
        with:
          version: v0.9.1
      - name: Cache Docker layers
        uses: actions/cache@04f198bf0b2a39f7230a4304bf07747a0bddf146
        with:
          path: /tmp/buildx-cache
          key: docker-cache-${{ github.head_ref }}
          restore-keys: docker-cache-master
      - name: Login to quay.io
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ENVOY_USERNAME_DEV }}
          password: ${{ secrets.QUAY_ENVOY_PASSWORD_DEV }}
      - name: Checkout PR
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prep for build
        run: |
          echo "${{ github.event.pull_request.head.sha }}" >SOURCE_VERSION
          echo "ENVOY_VERSION=$(cat ENVOY_VERSION)" >> $GITHUB_ENV
      - name: PR Multi-arch build & push of cilium-envoy
        uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf
        id: docker_build_ci
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILDER_IMAGE=quay.io/cilium/cilium-envoy-builder:master-archive-latest
            BAZEL_BUILD_OPTS=--remote_upload_local_results=false
          cache-from: type=local,src=/tmp/buildx-cache
          cache-to: type=local,dest=/tmp/buildx-cache,mode=max
          push: true
          tags: quay.io/${{ github.repository_owner }}/cilium-envoy-dev:${{ github.event.pull_request.head.sha }}
      - name: Envoy binary version check
        shell: bash
        run: |
          docker create -ti --name cilium-envoy quay.io/${{ github.repository_owner }}/cilium-envoy-dev:${{ github.event.pull_request.head.sha }} bash
          docker cp cilium-envoy:/usr/bin/cilium-envoy ./cilium-envoy
          docker rm -fv cilium-envoy
          envoy_version=$(./cilium-envoy --version)
          echo ${envoy_version}
          [[ "${envoy_version}" == *"${{ github.event.pull_request.head.sha }}"* ]]
      - name: CI Image Digest
        shell: bash
        run: |
          echo "Digests:"
          echo "quay.io/${{ github.repository_owner }}/cilium-envoy-dev:${{ github.event.pull_request.head.sha }}@${{ steps.docker_build_ci.outputs.digest }}"
