name: CI Build & Push
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  build-and-push-prs:
    name: Build and push multi-arch images
    environment:
      name: ci-build
      deployment: false
    timeout-minutes: 360
    runs-on: ${{ vars.PROXY_BUILD_GITHUB_RUNNER }}
    outputs:
      sha: ${{ steps.tag.outputs.sha }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0-28

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Cache Docker layers
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /tmp/buildx-cache
          key: docker-cache-${{ github.head_ref }}
          restore-keys: docker-cache-main

      - name: Login to quay.io
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ENVOY_USERNAME_DEV }}
          password: ${{ secrets.QUAY_ENVOY_PASSWORD_DEV }}

      - name: Checkout PR
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Prep for build
        run: |
          echo "${{ github.event.pull_request.head.sha }}" >SOURCE_VERSION
          VERSION=$(cat ENVOY_VERSION)
          if [[ "$VERSION" =~ ^envoy-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            PATCH="${VERSION#envoy-}"
            MINOR="${PATCH%.*}"
            echo "ENVOY_MINOR_RELEASE=v${MINOR}" >> $GITHUB_ENV
            echo "ENVOY_PATCH_RELEASE=v${PATCH}" >> $GITHUB_ENV
          else
            echo "Invalid ENVOY_VERSION format: '$VERSION'" && exit 1
          fi
          echo "BUILDER_DOCKER_HASH=$(git ls-tree --full-tree HEAD -- ./Dockerfile.builder | awk '{ print $3 }')" >> $GITHUB_ENV

      - name: Checking if cilium-envoy-builder image exists
        id: cilium-builder-tag-in-repositories
        shell: bash
        run: |
          if docker buildx imagetools inspect quay.io/${{ github.repository_owner }}/cilium-envoy-builder-dev:${{ env.BUILDER_DOCKER_HASH }} &>/dev/null; then
            echo exists="true" >> $GITHUB_OUTPUT
          else
            echo exists="false" >> $GITHUB_OUTPUT
          fi

      - name: PR Multi-arch build & push of Builder image (dev)
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        if: steps.cilium-builder-tag-in-repositories.outputs.exists == 'false'
        id: docker_build_builder_ci
        with:
          provenance: false
          context: .
          file: ./Dockerfile.builder
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/${{ github.repository_owner }}/cilium-envoy-builder-dev:${{ env.BUILDER_DOCKER_HASH }}

      - name: CI Builder Image Digest
        if: steps.cilium-builder-tag-in-repositories.outputs.exists == 'false'
        shell: bash
        run: |
          echo "Digests:"
          echo "quay.io/${{ github.repository_owner }}/cilium-envoy-builder-dev:${{ env.BUILDER_DOCKER_HASH }}@${{ steps.docker_build_builder_ci.outputs.digest }}"

      - name: PR Multi-arch build & push of cilium-envoy
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        id: docker_build_ci
        with:
          provenance: false
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILDER_BASE=quay.io/cilium/cilium-envoy-builder-dev:${{ env.BUILDER_DOCKER_HASH }}
            ARCHIVE_IMAGE=quay.io/${{ github.repository_owner }}/cilium-envoy-builder:main-archive-latest
            BAZEL_BUILD_OPTS=--remote_upload_local_results=false
          cache-from: type=local,src=/tmp/buildx-cache
          cache-to: type=local,dest=/tmp/buildx-cache,mode=max
          push: true
          tags: quay.io/${{ github.repository_owner }}/cilium-envoy-dev:${{ github.event.pull_request.head.sha }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Sign Container Image
        run: |
          cosign sign -y quay.io/${{ github.repository_owner }}/cilium-envoy-dev@${{ steps.docker_build_ci.outputs.digest }}

      - name: Install Bom
        shell: bash
        env:
          # renovate: datasource=github-releases depName=kubernetes-sigs/bom
          BOM_VERSION: v0.7.1
        run: |
          curl -L https://github.com/kubernetes-sigs/bom/releases/download/${{ env.BOM_VERSION }}/bom-amd64-linux -o bom
          sudo mv ./bom /usr/local/bin/bom
          sudo chmod +x /usr/local/bin/bom

      - name: Generate SBOM
        shell: bash
        # To-Do: generate SBOM from source after https://github.com/kubernetes-sigs/bom/issues/202 is fixed
        run: |
          bom generate -o sbom_cilium-envoy_${{ github.event.pull_request.head.sha }}.spdx --format=json --image=quay.io/${{ github.repository_owner }}/cilium-envoy-dev:${{ github.event.pull_request.head.sha }}

      - name: Attach SBOM to container images
        run: |
          cosign attach sbom --sbom sbom_cilium-envoy_${{ github.event.pull_request.head.sha }}.spdx quay.io/${{ github.repository_owner }}/cilium-envoy-dev@${{ steps.docker_build_ci.outputs.digest }}

      - name: Sign SBOM Image
        run: |
          docker_build_ci_digest="${{ steps.docker_build_ci.outputs.digest }}"
          image_name="quay.io/${{ github.repository_owner }}/cilium-envoy-dev:${docker_build_ci_digest/:/-}.sbom"
          docker_build_ci_sbom_digest="sha256:$(docker buildx imagetools inspect --raw ${image_name} | sha256sum | head -c 64)"
          cosign sign -y "quay.io/${{ github.repository_owner }}/cilium-envoy-dev@${docker_build_ci_sbom_digest}"

      - name: Envoy binary version check
        shell: bash
        run: |
          envoy_version=$(docker run --rm quay.io/${{ github.repository_owner }}/cilium-envoy-dev:${{ github.event.pull_request.head.sha }} cilium-envoy --version)
          expected_version=$(echo ${{ env.ENVOY_PATCH_RELEASE }} | sed 's/^v//')
          echo ${envoy_version}
          [[ "${envoy_version}" == *"${{ github.event.pull_request.head.sha }}/$expected_version"* ]]

      - name: CI Image Digest
        shell: bash
        run: |
          echo "Digests:"
          echo "quay.io/${{ github.repository_owner }}/cilium-envoy-dev:${{ github.event.pull_request.head.sha }}@${{ steps.docker_build_ci.outputs.digest }}"

  cilium-intergration-tests:
    name: Cilium Integration Tests
    needs: build-and-push-prs
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    uses: ./.github/workflows/cilium-integration-tests.yaml
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      commit_ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  cilium-gateway-api-tests:
    name: Cilium Gateway API Tests
    needs: build-and-push-prs
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    uses: ./.github/workflows/cilium-gateway-api.yaml
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      commit_ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
