name: CI Build & Push
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push-prs:
    timeout-minutes: 360
    name: Build and push multi-arch images
    runs-on: ubuntu-20.04
    steps:
      - name: Add swap
        run: |
          set -x
          file="/mnt/swapfile"
          sudo swapoff "${file}"
          sudo fallocate -l 8G "${file}"
          sudo chmod 600 "${file}"
          sudo mkswap "${file}"
          sudo swapon "${file}"
          sudo swapon -s
          free -m
          df -h
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/buildx-cache
          key: docker-cache-${{ github.head_ref }}
          restore-keys: docker-cache-master
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ENVOY_USERNAME_DEV }}
          password: ${{ secrets.QUAY_ENVOY_PASSWORD_DEV }}
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prep for build
        run: |
          echo "${{ github.event.pull_request.head.sha }}" >SOURCE_VERSION
          echo "ENVOY_VERSION=$(cat ENVOY_VERSION)" >> $GITHUB_ENV
      - name: PR Multi-arch build & push of cilium-envoy
        uses: docker/build-push-action@v2
        id: docker_build_ci
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILDER_IMAGE=quay.io/cilium/cilium-envoy-builder:${{ env.ENVOY_VERSION }}-archive-latest
            BAZEL_BUILD_OPTS=--remote_upload_local_results=false
          cache-from: type=local,src=/tmp/buildx-cache
          cache-to: type=local,dest=/tmp/buildx-cache,mode=max
          push: true
          tags: quay.io/${{ github.repository_owner }}/cilium-envoy-dev:${{ github.event.pull_request.head.sha }}
      - name: Envoy binary version check
        shell: bash
        run: |
          docker create -ti --name cilium-envoy quay.io/${{ github.repository_owner }}/cilium-envoy-dev:${{ github.event.pull_request.head.sha }} bash
          docker cp cilium-envoy:/usr/bin/cilium-envoy ./cilium-envoy
          docker rm -fv cilium-envoy
          envoy_version=$(./cilium-envoy --version)
          echo ${envoy_version}
          [[ "${envoy_version}" == *"${{ github.event.pull_request.head.sha }}"* ]]
      - name: CI Image Digest
        shell: bash
        run: |
          echo "Digests:"
          echo "quay.io/${{ github.repository_owner }}/cilium-envoy-dev:${{ github.event.pull_request.head.sha }}@${{ steps.docker_build_ci.outputs.digest }}"
