name: Validate Renovate configuration

on:
  pull_request:
    paths:
      - '.github/renovate.json5'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Renovate configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout configuration
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # this step uses latest renovate slim release
      - name: Validate configuration
        run: >
          # renovate: datasource=docker
          export RENOVATE_IMAGE=ghcr.io/renovatebot/renovate:39.98.0@sha256:43e35242449741dab5e60510ba39704a720422f83fdaa495709bc1e0f141625d
          docker run --rm --entrypoint "renovate-config-validator"
          -v "${{ github.workspace }}/.github/renovate.json5":"/renovate.json5"
          ${RENOVATE_IMAGE} "/renovate.json5"

