// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/filter/network/rbac/v2/rbac.proto

package v2

import (
	fmt "fmt"
	v2alpha "github.com/cilium/proxy/go/envoy/config/rbac/v2alpha"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lyft/protoc-gen-validate/validate"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RBAC_EnforcementType int32

const (
	// Apply RBAC policies when the first byte of data arrives on the connection.
	RBAC_ONE_TIME_ON_FIRST_BYTE RBAC_EnforcementType = 0
	// Continuously apply RBAC policies as data arrives. Use this mode when
	// using RBAC with message oriented protocols such as Mongo, MySQL, Kafka,
	// etc. when the protocol decoders emit dynamic metadata such as the
	// resources being accessed and the operations on the resources.
	RBAC_CONTINUOUS RBAC_EnforcementType = 1
)

var RBAC_EnforcementType_name = map[int32]string{
	0: "ONE_TIME_ON_FIRST_BYTE",
	1: "CONTINUOUS",
}

var RBAC_EnforcementType_value = map[string]int32{
	"ONE_TIME_ON_FIRST_BYTE": 0,
	"CONTINUOUS":             1,
}

func (x RBAC_EnforcementType) String() string {
	return proto.EnumName(RBAC_EnforcementType_name, int32(x))
}

func (RBAC_EnforcementType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8ec60cc393c44598, []int{0, 0}
}

// RBAC network filter config.
//
// Header should not be used in rules/shadow_rules in RBAC network filter as
// this information is only available in :ref:`RBAC http filter <config_http_filters_rbac>`.
type RBAC struct {
	// Specify the RBAC rules to be applied globally.
	// If absent, no enforcing RBAC policy will be applied.
	Rules *v2alpha.RBAC `protobuf:"bytes,1,opt,name=rules,proto3" json:"rules,omitempty"`
	// Shadow rules are not enforced by the filter but will emit stats and logs
	// and can be used for rule testing.
	// If absent, no shadow RBAC policy will be applied.
	ShadowRules *v2alpha.RBAC `protobuf:"bytes,2,opt,name=shadow_rules,json=shadowRules,proto3" json:"shadow_rules,omitempty"`
	// The prefix to use when emitting statistics.
	StatPrefix string `protobuf:"bytes,3,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	// RBAC enforcement strategy. By default RBAC will be enforced only once
	// when the first byte of data arrives from the downstream. When used in
	// conjunction with filters that emit dynamic metadata after decoding
	// every payload (e.g., Mongo, MySQL, Kafka) set the enforcement type to
	// CONTINUOUS to enforce RBAC policies on every message boundary.
	EnforcementType      RBAC_EnforcementType `protobuf:"varint,4,opt,name=enforcement_type,json=enforcementType,proto3,enum=envoy.config.filter.network.rbac.v2.RBAC_EnforcementType" json:"enforcement_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RBAC) Reset()         { *m = RBAC{} }
func (m *RBAC) String() string { return proto.CompactTextString(m) }
func (*RBAC) ProtoMessage()    {}
func (*RBAC) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec60cc393c44598, []int{0}
}

func (m *RBAC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RBAC.Unmarshal(m, b)
}
func (m *RBAC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RBAC.Marshal(b, m, deterministic)
}
func (m *RBAC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RBAC.Merge(m, src)
}
func (m *RBAC) XXX_Size() int {
	return xxx_messageInfo_RBAC.Size(m)
}
func (m *RBAC) XXX_DiscardUnknown() {
	xxx_messageInfo_RBAC.DiscardUnknown(m)
}

var xxx_messageInfo_RBAC proto.InternalMessageInfo

func (m *RBAC) GetRules() *v2alpha.RBAC {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *RBAC) GetShadowRules() *v2alpha.RBAC {
	if m != nil {
		return m.ShadowRules
	}
	return nil
}

func (m *RBAC) GetStatPrefix() string {
	if m != nil {
		return m.StatPrefix
	}
	return ""
}

func (m *RBAC) GetEnforcementType() RBAC_EnforcementType {
	if m != nil {
		return m.EnforcementType
	}
	return RBAC_ONE_TIME_ON_FIRST_BYTE
}

func init() {
	proto.RegisterEnum("envoy.config.filter.network.rbac.v2.RBAC_EnforcementType", RBAC_EnforcementType_name, RBAC_EnforcementType_value)
	proto.RegisterType((*RBAC)(nil), "envoy.config.filter.network.rbac.v2.RBAC")
}

func init() {
	proto.RegisterFile("envoy/config/filter/network/rbac/v2/rbac.proto", fileDescriptor_8ec60cc393c44598)
}

var fileDescriptor_8ec60cc393c44598 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0xdd, 0x40, 0x13, 0x8a, 0x01, 0xb2, 0x18, 0x25, 0x5c, 0x5c, 0xd0, 0x03, 0xf1, 0xd0,
	0xc5, 0x19, 0x0f, 0x1e, 0x3c, 0x38, 0x9c, 0x09, 0x07, 0x37, 0x52, 0xc6, 0x41, 0x2f, 0x4d, 0x19,
	0x1d, 0x2c, 0xce, 0x75, 0x29, 0x75, 0xb0, 0xaf, 0xe6, 0xc9, 0xcf, 0xe0, 0xb7, 0xf0, 0x5b, 0x98,
	0xb5, 0x33, 0x8a, 0x27, 0x4e, 0x7d, 0x79, 0xef, 0xf7, 0xff, 0xbf, 0x7f, 0xfa, 0x00, 0xa4, 0x69,
	0xce, 0x0a, 0x2b, 0x64, 0x69, 0x14, 0x2f, 0xac, 0x28, 0x4e, 0x04, 0xe5, 0x56, 0x4a, 0xc5, 0x9a,
	0xf1, 0x17, 0x8b, 0xcf, 0x48, 0x68, 0xe5, 0xb6, 0x7c, 0x61, 0xc6, 0x99, 0x60, 0xc6, 0x99, 0xe4,
	0xa1, 0xe2, 0xa1, 0xe2, 0x61, 0xc5, 0x43, 0xc9, 0xe5, 0x76, 0xef, 0x7c, 0xcb, 0xb4, 0x72, 0x21,
	0x49, 0xb6, 0x24, 0x7f, 0xac, 0x7a, 0x27, 0x39, 0x49, 0xe2, 0x39, 0x11, 0xd4, 0xfa, 0x29, 0xaa,
	0xc1, 0xd1, 0x82, 0x2d, 0x98, 0x2c, 0xad, 0xb2, 0x52, 0xdd, 0xfe, 0xa7, 0x0e, 0xea, 0xc8, 0xb9,
	0x1b, 0x1a, 0xd7, 0x60, 0x9f, 0xbf, 0x25, 0x74, 0xd5, 0xd5, 0x4c, 0x6d, 0xd0, 0xb4, 0x4f, 0xe1,
	0x56, 0xa4, 0x2a, 0x83, 0xdc, 0x06, 0x4b, 0x1e, 0x29, 0xda, 0x70, 0xc0, 0xe1, 0x6a, 0x49, 0xe6,
	0x6c, 0x8d, 0x95, 0x5a, 0xdf, 0x4d, 0xdd, 0x54, 0x22, 0x24, 0x3d, 0x2e, 0x40, 0x73, 0x25, 0x88,
	0xc0, 0x19, 0xa7, 0x51, 0xbc, 0xe9, 0xd6, 0x4c, 0x6d, 0xd0, 0x70, 0x1a, 0xef, 0x5f, 0x1f, 0xb5,
	0x3a, 0xd7, 0x4d, 0x0d, 0x81, 0x72, 0x3a, 0x96, 0x43, 0x63, 0x0e, 0x3a, 0x34, 0x8d, 0x18, 0x0f,
	0xe9, 0x2b, 0x4d, 0x05, 0x16, 0x45, 0x46, 0xbb, 0x75, 0x53, 0x1b, 0xb4, 0xec, 0x1b, 0xb8, 0xc3,
	0x27, 0xca, 0xed, 0xd0, 0xfd, 0x75, 0x08, 0x8a, 0x8c, 0xa2, 0x36, 0xdd, 0x6e, 0xf4, 0x6f, 0x41,
	0xfb, 0x1f, 0x63, 0xf4, 0xc0, 0xb1, 0xef, 0xb9, 0x38, 0x18, 0x3d, 0xba, 0xd8, 0xf7, 0xf0, 0xc3,
	0x08, 0x4d, 0x02, 0xec, 0x3c, 0x05, 0x6e, 0x67, 0xcf, 0x68, 0x01, 0x30, 0xf4, 0xbd, 0x60, 0xe4,
	0x4d, 0xfd, 0xe9, 0xa4, 0xa3, 0x39, 0xf7, 0xe0, 0x32, 0x66, 0x2a, 0x4e, 0xc6, 0xd9, 0xa6, 0xd8,
	0x25, 0x99, 0xd3, 0x40, 0x33, 0x12, 0x8e, 0xcb, 0xa3, 0x8c, 0xb5, 0x67, 0x3d, 0xb7, 0x67, 0x07,
	0xf2, 0x42, 0x57, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xa0, 0x54, 0xc1, 0x4d, 0x02, 0x00,
	0x00,
}
